spring:
  datasource:
  muliti-db:
    defaultDb: db1
    dataSources:
      write:
        url: url
        username: root
        password: 123456
#      {
#        db1: {url: url1, username: username, password: 123},
#        db2: {url: url2}
#      }