server:
  port: 80


#mybatis-plus:
#  configuration-properties:
#    prefix:
#      blobType: BLOB
#      boolValue: TRUE
mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/flowable65?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
#  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时,会自动将数据库表结构升级至新版本。
  database-schema-update: true
  common:
    app:
#      idm-url: http://127.0.0.1://80/flowable-idm
      idm-url: ${bath.path}/flowable-idm
